Hw 2 2
yurkohudyma/EpamLabHW pull request #4
Opened 2022-01-30 19:33 UTC by yurkohudyma

Homework2 recommitted

2022-01-31 23:02 UTC, romanbobak requested changes
Hi Yura! Well done! Thank you for efforts and dedicated time! 
I left several minor comments mostly regarding code style. Please take a look.
Please also delete file 'application.properties' that is empty and is not used.

Also I noticed issue related to the project structure.
Lets get together via Teams and resolve it.

Thank you again for resolving remarks!

2022-02-01 08:17 UTC, yurkohudyma commented on LabHomework2/pom.xml
> +		<dependency>
I'd deleted this dep before. Seems like some version collision has taken place.

2022-02-01 08:27 UTC, yurkohudyma commented on LabHomework2/src/main/java/com/epam/spring/src/main/java/com/epam/spring/homework2/beans/BeanB.java
> +}
Tried both Ctrl-Alt-L and namely reformat Ctrl-Alt-Shift-L: no lines changed. What exactly is out of the style?

2022-02-01 08:29 UTC, yurkohudyma commented on LabHomework2/src/main/java/com/epam/spring/src/main/java/com/epam/spring/homework2/beans/BeanB.java
> +}
Will comply

2022-02-01 08:31 UTC, yurkohudyma commented on LabHomework2/src/main/java/com/epam/spring/src/main/java/com/epam/spring/homework2/beans/BeanC.java
> +}
Will do

2022-02-01 08:32 UTC, yurkohudyma commented on LabHomework2/src/main/java/com/epam/spring/src/main/java/com/epam/spring/homework2/beans/BeanD.java
> +}
Affirmative

2022-02-01 08:33 UTC, yurkohudyma commented on LabHomework2/src/main/java/com/epam/spring/src/main/java/com/epam/spring/homework2/beans/BeanD.java
> +
Done

2022-02-01 08:33 UTC, yurkohudyma commented on LabHomework2/src/main/java/com/epam/spring/src/main/java/com/epam/spring/homework2/beans/BeanE.java
> +	public void setName() {
Done

2022-02-01 08:34 UTC, yurkohudyma commented on LabHomework2/src/main/java/com/epam/spring/src/main/java/com/epam/spring/homework2/beans/BeanE.java
> +		}
Done

2022-02-01 08:35 UTC, yurkohudyma commented on LabHomework2/src/main/java/com/epam/spring/src/main/java/com/epam/spring/homework2/config/AppConfig.java
> +public BeanA getBeanA() {
Done

2022-02-01 08:35 UTC, yurkohudyma commented on LabHomework2/src/main/java/com/epam/spring/src/main/java/com/epam/spring/homework2/extensions/BeanPostProcessorImpl.java
> +				fieldName = bean.getClass().getDeclaredField("name");
Thanxalot!

2022-02-01 08:37 UTC, yurkohudyma commented on LabHomework2/src/main/java/com/epam/spring/src/main/java/com/epam/spring/App.java
> +
done

2022-02-01 08:38 UTC, yurkohudyma commented on LabHomework2/src/main/java/com/epam/spring/src/main/java/com/epam/spring/App.java
> +		for (String contextgetBeanDefinitionNames : context.getBeanDefinitionNames()) {
Done

2022-02-01 08:41 UTC, yurkohudyma commented on LabHomework2/src/main/java/com/epam/spring/src/main/java/com/epam/spring/App.java
> +	public static void outXmlContext(String beanName) {
Done

2022-02-01 08:42 UTC, yurkohudyma commented on LabHomework2/src/main/java/com/epam/spring/src/main/java/com/epam/spring/homework2/beans/BeanB.java
> +
Done

2022-02-01 09:43 UTC, romanbobak commented on LabHomework2/pom.xml
> +		<dependency>
Thank you!

2022-02-01 09:44 UTC, romanbobak commented on LabHomework2/src/main/java/com/epam/spring/src/main/java/com/epam/spring/homework2/beans/BeanB.java
> +}
Thanks!

2022-02-01 09:44 UTC, romanbobak commented on LabHomework2/src/main/java/com/epam/spring/src/main/java/com/epam/spring/homework2/beans/BeanB.java
> +
Thanks!

2022-02-01 09:45 UTC, romanbobak commented on LabHomework2/src/main/java/com/epam/spring/src/main/java/com/epam/spring/homework2/beans/BeanC.java
> +}
Thanks!

2022-02-01 09:45 UTC, romanbobak commented on LabHomework2/src/main/java/com/epam/spring/src/main/java/com/epam/spring/homework2/beans/BeanD.java
> +}
Thanks!

2022-02-01 09:46 UTC, romanbobak commented on LabHomework2/src/main/java/com/epam/spring/src/main/java/com/epam/spring/homework2/beans/BeanD.java
> +
Thanks!

2022-02-01 09:48 UTC, romanbobak commented on LabHomework2/src/main/java/com/epam/spring/src/main/java/com/epam/spring/homework2/beans/BeanE.java
> +	public void setName() {
Thanks!

2022-02-01 09:50 UTC, romanbobak commented on LabHomework2/src/main/java/com/epam/spring/src/main/java/com/epam/spring/homework2/beans/BeanE.java
> +		}
Thanks!

2022-02-01 09:51 UTC, romanbobak commented on LabHomework2/src/main/java/com/epam/spring/src/main/java/com/epam/spring/homework2/config/AppConfig.java
> +public BeanA getBeanA() {
Thanks!

2022-02-01 09:51 UTC, romanbobak commented on LabHomework2/src/main/java/com/epam/spring/src/main/java/com/epam/spring/App.java
> +
Thanks!

2022-02-01 09:52 UTC, romanbobak commented on LabHomework2/src/main/java/com/epam/spring/src/main/java/com/epam/spring/App.java
> +		for (String contextgetBeanDefinitionNames : context.getBeanDefinitionNames()) {
Thanks!

2022-02-01 09:52 UTC, romanbobak commented on LabHomework2/src/main/java/com/epam/spring/src/main/java/com/epam/spring/App.java
> +	public static void outXmlContext(String beanName) {
Thanks!

2022-02-01 13:14 UTC, merged